"""
Django settings for Portafolio project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from decouple import config, UndefinedValueError
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', cast=str)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', cast=bool)

ALLOWED_HOSTS = []

# Para producción (DEBUG=False)
if not DEBUG:
    ALLOWED_HOSTS = [
        'portafolio-8pck.onrender.com',  # Dominio original de Render
        'www.denisbravo.com',            # Tu dominio personalizado con www
        'denisbravo.com',                # Tu dominio sin www
        'localhost',                     # Para pruebas locales
        '127.0.0.1',                     # Para pruebas locales
    ]

try:
    external_hostname = config('RENDER_EXTERNAL_HOSTNAME')
    ALLOWED_HOSTS.append(external_hostname)
except UndefinedValueError:
    pass  # La variable no existe en entorno local, no hay problema

# Application definition
INSTALLED_APPS = [
    'whitenoise.runserver_nostatic',  # Soporte para desarrollo (opcional)
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary',  # Para manejar imágenesAdd commentMore actions
    'cloudinary_storage',  # Almacenamiento de Cloudinary
    'django.contrib.staticfiles',  # Para archivos estáticos
    'principal',
    'dashboard',
    'django_plotly_dash.apps.DjangoPlotlyDashConfig', #configuracion adicional para utilizzr dash
    'dpd_static_support',  # Requerido por django-plotly-dash
    'channels',  # Para soporte de WebSocket en Dash #configuracion adicional para utilizzr dash
]


CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:8000",  # Asegúrate de que tu URL esté permitida
]

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Para servir archivos estáticos en producción
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django_plotly_dash.middleware.BaseMiddleware',  # Asegúrate de que esté en este orden #configuracion adicional para utilizzr dash
    'django_plotly_dash.middleware.ExternalRedirectionMiddleware',  # Lo puedes dejar aquí #configuracion adicional para utilizzr dash
]

# Configuración para permitir que se cargue en un iframe desde el mismo dominio
#configuracion adicional para utilizzr dash
X_FRAME_OPTIONS = 'SAMEORIGIN'



ROOT_URLCONF = 'Portafolio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Portafolio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {  # Base de datos principal (portafolio)
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('DB_NAME_DEFAULT', cast=str),
        'USER': config('DB_USER_DEFAULT', cast=str),
        'PASSWORD': config('DB_PASSWORD_DEFAULT', cast=str),
        'HOST': config('DB_HOST_DEFAULT', cast=str),
        'PORT': config('DB_PORT_DEFAULT', cast=str),
    },
    'dashboard': {  # Base de datos del dashboard
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('DB_NAME_DASHBOARD', cast=str),  
        'USER': config('DB_USER_DASHBOARD', cast=str),
        'PASSWORD': config('DB_PASSWORD_DASHBOARD', cast=str),
        'HOST': config('DB_HOST_DASHBOARD', cast=str),
        'PORT': config('DB_PORT_DASHBOARD', cast=str),
    }
}

DATABASE_ROUTERS = ['Portafolio.database_router.DashboardRouter']


#Media
#MEDIA_URL = '/media/'
#MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# 3. Configuración básica de archivos estáticos (ya la tienes)
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]  # Desarrollo
STATIC_ROOT = BASE_DIR / "staticfiles"     # Producción

# 4. Configuración específica para producción (Render)
if not config('DEBUG', default=True, cast=bool):
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
    # Opciones adicionales recomendadas para Whitenoise:
    WHITENOISE_USE_FINDERS = True
    WHITENOISE_MANIFEST_STRICT = False

   
# Configuración para los componentes de Plotly Dash
PLOTLY_COMPONENTS = [
    'dash_core_components',
    'dash_html_components',
    'dash_renderer',
    'dpd_static_support',  # Requerido por Django Plotly Dash
    'dash_bootstrap_components',  # Si usas Bootstrap en Dash
]

#configuracion adicional para utilizzr dash
DASH_COMPONENTS = {
    'path_to_components': 'your_static_folder'
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


###################################################################
#configuracion adicional para utilizzr dash
ASGI_APPLICATION = 'Portafolio.asgi.application' 

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',  # Para desarrollo local
    },
}

# Configuración de Cloudinary para manejar imágenesAdd commentMore actions
CLOUDINARY_STORAGE = {
    'cloud_name': config('CLOUDINARY_CLOUD_NAME', cast=str),
    'api_key': config('CLOUDINARY_API_KEY', cast=str),
    'api_secret': config('CLOUDINARY_API_SECRET', cast=str),
    'secure': True,  # Usa HTTPS para las URLs de Cloudinary
}
# Configuración de almacenamiento de archivos multimedia
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
MEDIA_URL = '/media/'