"""
Django settings for Portafolio project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&zs040g=)8dkc+pf5g2d@x!@rlwiwdhvqtb(k46yw(b=we*&!1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',  # Déjalo solo una vez aquí
    'principal',
    'dashboard',
    'django_plotly_dash.apps.DjangoPlotlyDashConfig', #configuracion adicional para utilizzr dash
    'dpd_static_support',  # Requerido por django-plotly-dash
    'channels',  # Para soporte de WebSocket en Dash #configuracion adicional para utilizzr dash
]


CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:8000",  # Asegúrate de que tu URL esté permitida
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django_plotly_dash.middleware.BaseMiddleware',  # Asegúrate de que esté en este orden #configuracion adicional para utilizzr dash
    'django_plotly_dash.middleware.ExternalRedirectionMiddleware',  # Lo puedes dejar aquí #configuracion adicional para utilizzr dash
]

# Configuración para permitir que se cargue en un iframe desde el mismo dominio
#configuracion adicional para utilizzr dash
X_FRAME_OPTIONS = 'SAMEORIGIN'



ROOT_URLCONF = 'Portafolio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Portafolio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {  # Base de datos principal (portafolio)
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'portafolio',
        'USER': 'Dnns',
        'PASSWORD': 'Maria1961.',
        'HOST': 'localhost',
        'PORT': '3306',
    },
    'dashboard': {  # Base de datos del dashboard
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'DIPUTADOS_ACT',   
        'USER': 'Dnns',
        'PASSWORD': 'Maria1961.',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}

DATABASE_ROUTERS = ['Portafolio.database_router.DashboardRouter']


#Media
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

#STATIC_URL = 'static/'

#configuracion adicional para utilizzr dash
STATIC_URL = '/static/'

# Estos son necesarios para que Dash pueda servir los archivos estáticos
#configuracion adicional para utilizzr dash
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

#configuracion adicional para utilizzr dash
STATIC_ROOT = BASE_DIR / "staticfiles"  # Esto es para la recopilación de archivos estáticos en producción.

# Configuración para los componentes de Plotly Dash
PLOTLY_COMPONENTS = [
    'dash_core_components',
    'dash_html_components',
    'dash_renderer',
    'dpd_static_support',  # Requerido por Django Plotly Dash
    'dash_bootstrap_components',  # Si usas Bootstrap en Dash
]

#configuracion adicional para utilizzr dash
DASH_COMPONENTS = {
    'path_to_components': 'your_static_folder'
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


###################################################################
#configuracion adicional para utilizzr dash
ASGI_APPLICATION = 'Portafolio.asgi.application' 

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',  # Para desarrollo local
    },
}
