# Generated by Django 5.1.3 on 2024-12-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(default='Cargo por defecto', max_length=100)),
                ('empresa', models.CharField(default='Empresa por defecto', max_length=100)),
                ('descripcion', models.TextField(default='Descripción por defecto')),
                ('fecha_inicio', models.DateField(default='2000-01-01')),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Formacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('Pregrado', 'Pregrado'), ('Certificado', 'Certificado')], default='Pregrado', max_length=50)),
                ('institucion', models.CharField(default='Institución por defecto', max_length=200)),
                ('titulo', models.CharField(default='Título por defecto', max_length=200)),
                ('fecha_inicio', models.DateField(default='2000-01-01')),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(default='Nombre por defecto', max_length=100)),
                ('profesion', models.TextField(default='Profesión por defecto', help_text='Lista tus profesiones separadas por comas')),
            ],
        ),
        migrations.DeleteModel(
            name='Experiencia',
        ),
        migrations.RemoveField(
            model_name='acercade',
            name='nombre',
        ),
        migrations.AddField(
            model_name='acercade',
            name='correo',
            field=models.EmailField(default='correo@ejemplo.com', max_length=254),
        ),
        migrations.AddField(
            model_name='acercade',
            name='direccion',
            field=models.CharField(default='Dirección no especificada', max_length=255),
        ),
        migrations.AddField(
            model_name='acercade',
            name='fecha_nacimiento',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='acercade',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acercade',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acercade',
            name='otra_red_social',
            field=models.URLField(blank=True, help_text='Opcionalmente agrega otra red social', null=True),
        ),
        migrations.AddField(
            model_name='acercade',
            name='telefono',
            field=models.CharField(default='000000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='acercade',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='email',
            field=models.EmailField(default='correo@ejemplo.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='mensaje',
            field=models.TextField(default='Mensaje por defecto'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(default='Nombre por defecto', max_length=100),
        ),
        migrations.AlterField(
            model_name='habilidad',
            name='categoria',
            field=models.CharField(choices=[('lenguaje', 'Lenguaje de Programación'), ('tecnologia', 'Tecnología o Software')], default='lenguaje', max_length=10),
        ),
        migrations.AlterField(
            model_name='habilidad',
            name='nivel',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='habilidad',
            name='nombre',
            field=models.CharField(default='Habilidad por defecto', max_length=50),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='categoria',
            field=models.CharField(choices=[('dashboard', 'Proyectos Interactivos'), ('notebook', 'Notebooks en GitHub')], default='dashboard', max_length=10),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.TextField(default='Descripción por defecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='enlace',
            field=models.URLField(default='https://ejemplo.com'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='titulo',
            field=models.CharField(default='Título por defecto', max_length=100),
        ),
    ]
