# Generated by Django 5.1.3 on 2025-01-30 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_experiencialaboral_formacion_portada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='enlace',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='titulo',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='category',
            field=models.CharField(choices=[('notebooks', 'Notebooks (GitHub)'), ('dashboards', 'Dashboards & Apps Interactivas'), ('web', 'Web Development')], default='Otros', max_length=20),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='description',
            field=models.TextField(default='Mensaje por defecto'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='skills',
            field=models.CharField(default='Habilidades por defecto', max_length=255),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='title',
            field=models.CharField(default='Titulo por defecto', max_length=100),
        ),
    ]
