# Generated by Django 5.1.3 on 2025-02-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_remove_proyecto_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='category',
            field=models.CharField(choices=[('notebooks', 'Notebooks (GitHub)'), ('dashboards & Apps Interactivas', 'Dashboards & Apps Interactivas'), ('web Development', 'Web Development')], default='Otros', max_length=40),
        ),
    ]
