# Generated by Django 5.1.3 on 2025-02-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_alter_proyecto_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='acercade',
            name='cv',
            field=models.FileField(blank=True, help_text='Sube tu CV en formato PDF', null=True, upload_to='cv/'),
        ),
    ]
